### PR TITLE
Added queue implementation

### PR DESCRIPTION
**Pull request by Vadko**
https://user-images.githubusercontent.com/9297785/221294664-11e866f6-a415-4614-a5ae-3c680dd1d4ab.mov

* Added promise-queue to organise pool for async requests
* Splitted message handler to sequence and parallel parts due to ChatGPT limitation of request processing
* Added queue indication for upcoming messages

### CODE REVIEW

**Comment by RainEggplant** [comment]
Hi @Vadko! Thank you for your pull request.

I really appreciate your contribution and have made some modifications to the code to fix a bug in the asynchronous logic. Here are the changes:

<details>
<summary>Changes:</summary>

1. I use a global counter `_queueLength` to track the number of queued requests. Because of asynchronous execution, a new request may arrive before previous ones are added to the queue, causing `Queue.getQueueLength` to undercount the actual number of queued requests.
2. I removed sending the queue position in the first receipt message because the position cannot be determined before the request is added to the queue.
3. I removed `_orderRequestsQueue` because it seems unnecessary, given that there can only be one `_updateQueue` function running at a time due to the `_apiRequestsQueue`.
</details>

Once again, thank you for your contribution, and please let me know if you have any questions or feedback.

**Comment by RainEggplant** [comment]
Oh, I see. I'll add it back.

But I think we shouldn't use `await` here, as that will make the execution sequential. What do you think?

https://github.com/Vadko/chatgpt-telegram-bot/blob/b4e0f8d4ea51374c5dd37586e732c761a701d885/src/handlers/chat.ts#L151

**Comment by Vadko** [comment]
I think await here doesn't wait for execution of promises execution but instead just for adding promise to queue. But, anyway, await isnt required here.

**Comment by RainEggplant** [comment]
Hi, after researching the [TS doc](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/promise-queue/index.d.ts), I found `Queue.add` just forwards the promise that the input function returns, not returns a promise to join the queue, which I tested and found to be true. So I'll drop the `await` here.

**Pull request merged**
